# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401
from peewee import *

from swagger_server.models.base_model_ import FlaskModel
from swagger_server import util


class Expression(Model, FlaskModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    id = AutoField()
    created = DateTimeField(default=datetime.now)
    updated = DateTimeField(default=datetime.now)

    @classmethod
    def from_dict(cls, dikt) -> 'Expression':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Expression of this Expression.  # noqa: E501
        :rtype: Expression
        """
        return util.deserialize_model(dikt, cls)
