# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401


from swagger_server import util

from peewee import *

from swagger_server.models.base_model_ import FlaskModel

from .expression import Expression

class Operator(Model, FlaskModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    id = AutoField()
    expression_id = ForeignKeyField(Expression)
    rank = IntegerField()
    value = CharField()
    type = IntegerField()

    @classmethod
    def from_dict(cls, dikt) -> 'Operator':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Operator of this Operator.  # noqa: E501
        :rtype: Operator
        """
        return util.deserialize_model(dikt, cls)

