# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import FlaskModel
from swagger_server import util


class ValueType(FlaskModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    @classmethod
    def from_dict(cls, dikt) -> 'ValueType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ValueType of this ValueType.  # noqa: E501
        :rtype: ValueType
        """
        return util.deserialize_model(dikt, cls)
